import React, { useEffect, useState } from "react";
import Head from "next/head";
import { Wrapper } from "@/components/styles/general";
import styled from "styled-components";
import { colors } from "@/constants/colors";
import { DragDropContext, Draggable, Droppable } from "@hello-pangea/dnd";
import { useRouter } from "next/router";
import CountreeLayout from "@/layouts/dashboard/CountreeLayout";

export default function Home() {
  const router = useRouter();
  // useEffect(() => {
  //   router.push("/dashboard/taskboard");
  // }, [router]);
  return (
    <>
      <Head>
        <title>Countree</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <CountreeLayout />
      </Wrapper>
    </>
  );
}
